# Q no: 01
Import the numpy package under the name np

In [6]:
import numpy as np

# Q no: 02
Create a vector with values ranging from 10 to 49

In [7]:
z=np.arange(10,49)

In [8]:
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

# Q no: 03
Reverse a vector (first element becomes last)

In [9]:
z[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

# Q no: 04
Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
vector=np.arange(0,9).reshape(3,3)

In [11]:
vector

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Q no: 05
Find indices of non-zero elements from [1,2,0,0,4,0]

In [12]:
x=[1,2,0,0,4,0]
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

# Q no: 06
Create a 3x3 identity matrix

In [13]:
g=np.identity(3)

In [14]:
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Q no: 07
Create a 3x3x3 array with random values

In [15]:
arr=np.random.rand(3,3,3)

In [16]:
arr

array([[[0.8061509 , 0.98707476, 0.04978563],
        [0.60795289, 0.54623883, 0.03472873],
        [0.91334831, 0.69847769, 0.24554668]],

       [[0.5388219 , 0.05857728, 0.53528786],
        [0.76990147, 0.93898193, 0.83443352],
        [0.97886112, 0.0946318 , 0.28866579]],

       [[0.43674043, 0.40120108, 0.21461183],
        [0.08221506, 0.90376337, 0.48042462],
        [0.92207922, 0.35325528, 0.43350278]]])

# Q no: 08
Create a 10x10 array with random values and find the minimum and
maximum values

In [17]:
f=np.random.rand(10,10)

In [18]:
f

array([[0.73824069, 0.82580746, 0.05426292, 0.71571995, 0.01137245,
        0.08906186, 0.07196501, 0.71974977, 0.13002266, 0.55690376],
       [0.22415645, 0.5311203 , 0.35235069, 0.4680297 , 0.2547114 ,
        0.04118804, 0.05168917, 0.55695903, 0.56523169, 0.89340173],
       [0.07948051, 0.13012798, 0.51088075, 0.87703223, 0.46838387,
        0.3238835 , 0.73841545, 0.81978209, 0.01543572, 0.73239264],
       [0.14292107, 0.11997832, 0.07034655, 0.59074703, 0.44571329,
        0.19162116, 0.41742877, 0.06214748, 0.63102949, 0.24944139],
       [0.03270788, 0.64626885, 0.44352112, 0.90099436, 0.22986435,
        0.27843353, 0.89574342, 0.48869953, 0.34915898, 0.03506977],
       [0.22151134, 0.0296127 , 0.57021161, 0.74229867, 0.30764388,
        0.77052472, 0.60274056, 0.81819842, 0.24471394, 0.63646974],
       [0.70598048, 0.97458473, 0.33155764, 0.92135372, 0.13457875,
        0.69838766, 0.78069861, 0.72330753, 0.97744126, 0.45701802],
       [0.86946624, 0.91475341, 0.0510063

In [19]:
m1=np.max(f)

In [20]:
m1

0.9827116202672677

In [21]:
m2=np.min(f)

In [22]:
m2

0.011372447874574476

# Q no: 09
Create a random vector of size 30 and find the mean value

In [23]:
v1=np.random.rand(30)

In [24]:
v1

array([0.78586106, 0.43366562, 0.1702551 , 0.02476491, 0.81333364,
       0.88335971, 0.48818502, 0.99668923, 0.70588698, 0.58073958,
       0.17589711, 0.6758854 , 0.53994511, 0.84005738, 0.33319308,
       0.38836539, 0.36892432, 0.83598439, 0.69285584, 0.20004007,
       0.7828641 , 0.96083709, 0.29563654, 0.77303404, 0.94544315,
       0.58068863, 0.56788794, 0.01982801, 0.64394519, 0.10816833])

In [25]:
m=np.mean(v1)

In [26]:
m

0.5537407323948632