In [4]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [5]:
swat_temp = 73
swat_rainfall = 67
swat_humidity = 43

In [6]:
swat_yield_apples = swat_temp * w1 + swat_rainfall * w2 + swat_humidity * w3
swat_yield_apples

56.8

In [7]:
swat = [73, 67, 43]
murree = [91, 88, 64]

In [8]:
weights = [w1, w2, w3]

In [9]:
list(zip(swat, weights))

[(73, 0.3), (67, 0.2), (43, 0.5)]

In [10]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

In [12]:
crop_yield(murree, weights)

76.9

In [13]:
import numpy as np

In [14]:
swat = np.array([73, 67, 43])

In [15]:
swat

array([73, 67, 43])

In [16]:
type(swat)

numpy.ndarray

In [17]:
swat.shape

(3,)

In [18]:
weights = np.array([w1, w2, w3])

In [19]:
weights

array([0.3, 0.2, 0.5])

In [20]:
weights[0]

0.3

In [21]:
np.dot(swat, weights)

56.8

In [23]:
(swat * weights).sum()

56.8

# Multi-dimensional Numpy arrays

In [24]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [25]:
climate_data.shape

(5, 3)

In [26]:
arr3 = np.array([
                    [
                        [11, 12, 13], 
                        [13, 14, 15]
                    ], 
                    [
                        [15, 16, 17], 
                        [17, 18, 19.5]
                    ]
                ])

In [28]:
arr3.shape

(2, 2, 3)

In [30]:
weights.dtype

dtype('float64')

In [31]:
arr3.dtype

dtype('float64')

In [32]:
np.arange(1,5)

array([1, 2, 3, 4])

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
z = np.arange(1,5)

In [35]:
z[::-1]

array([4, 3, 2, 1])

In [36]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
np.nonzero([4,3,0,0,3,0,0,5,0])

(array([0, 1, 4, 7]),)

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.random.random((2,2))

array([[0.73756523, 0.94122625],
       [0.82430775, 0.16921283]])

In [40]:
np.random.random((2,2,2))

array([[[0.47523685, 0.50795966],
        [0.6286287 , 0.20862447]],

       [[0.93778346, 0.05211642],
        [0.72579465, 0.68227904]]])

In [41]:
np.random.random((2,2,2,2))

array([[[[0.2824885 , 0.50749323],
         [0.566322  , 0.61894119]],

        [[0.70148245, 0.68991713],
         [0.24659033, 0.01257539]]],


       [[[0.41369624, 0.65109188],
         [0.06383114, 0.44206388]],

        [[0.86558082, 0.7343087 ],
         [0.01860991, 0.70734791]]]])