# Lab Tasks

#### Task01 
Replace all odd numbers in given array  with -1.                                                                       
task01=np.array([0,1,2,3,4,5,6,7,8,9])

In [1]:
import numpy as np

In [2]:
task01=np.array([0,1,2,3,4,5,6,7,8,9])

In [3]:
task01

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
for i in task01:
    if i%2!=0:
        task01[i]=-1

In [5]:
task01

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Task02 
Find the positions of
1) elements in x where its value is more  than its corresponding element in y.
2)elements in x where its value is equal to its corresponding element in y.                             
x=np.array([21,64,86,22,74,55,81,66,89])                                                                    
y=np.array([21,7,3,45,10,29,55,44,89])

In [6]:
x=np.array([21,64,86,22,74,55,81,66,89])

In [7]:
x

array([21, 64, 86, 22, 74, 55, 81, 66, 89])

In [8]:
y=np.array([21,7,3,45,10,29,55,44,89])

In [9]:
y

array([21,  7,  3, 45, 10, 29, 55, 44, 89])

 positions of elements in x where its value is more than its corresponding element in y.

In [10]:
for i in range(len(x)):
    if x[i]>y[i]:
        print(i,end=',')

1,2,4,5,6,7,

positions of elements in x where its value is equal to its corresponding element in y.

In [11]:
for i in range(len(x)):
    if x[i]==y[i]:
        print(i,end=',')

0,8,

### Task03

Generate a 2D array of random numbers of size (1000,3). find the mean of 3 random numbers and store the mean of each row in fourth column of that row.save result in csv file by the name mean.csv on your local disk with headers num1, num2 num3 and avervage. also find which row has the highest mean of all.

In [12]:
arr2d=np.random.rand(1000,3)

In [13]:
arr2d

array([[0.39323667, 0.6394314 , 0.36252106],
       [0.55616985, 0.65306829, 0.884103  ],
       [0.42144908, 0.92911412, 0.96655347],
       ...,
       [0.373153  , 0.46836664, 0.26040695],
       [0.86446074, 0.82746778, 0.71771681],
       [0.69594843, 0.44118409, 0.64880824]])

each list inside array is the item of an array

In [14]:
mean_row=[]

In [15]:
for row in arr2d:   #row is not a keyword. we can also use any other veriable.
    m=np.mean(row)
    mean_row.append(m) 

In [16]:
darray=np.array(mean_row)   #convert to numpy array

In [17]:
n=darray.reshape(1000,1)

In [18]:
new_array=np.concatenate((arr2d,n),axis=1)    #concatinate two arrays to specific axis. 0=row and 1=column
new_array

array([[0.39323667, 0.6394314 , 0.36252106, 0.46506304],
       [0.55616985, 0.65306829, 0.884103  , 0.69778038],
       [0.42144908, 0.92911412, 0.96655347, 0.77237222],
       ...,
       [0.373153  , 0.46836664, 0.26040695, 0.36730886],
       [0.86446074, 0.82746778, 0.71771681, 0.80321511],
       [0.69594843, 0.44118409, 0.64880824, 0.59531359]])

In [19]:
np.savetxt('mean.csv',new_array, fmt='%.18e',header='num1,num2,num3,mean', delimiter=' ')  #this function save array to file

In [20]:
np.max(new_array[:,3])

0.9339277299816967

In [21]:
np.min(new_array[:,3])

0.04305083486581851