In [2]:
import numpy as np

In [3]:
climate_data = np.genfromtxt('climate_data.csv', delimiter=',', skip_header=1)

#numpy.genfromtxt is a function in the NumPy library that can be used to read data from a 
#text file and create a NumPy array from the data.

In [4]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [5]:
climate_data.shape

(10000, 3)

In [6]:
weights = np.array([0.3, 0.2, 0.5])

(3,)

In [8]:
yields = climate_data @ weights    #mx(n=n)xy      resultant=mxy

In [15]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [10]:
yields.shape

(10000,)

In [12]:
a = np.array([[1, 2], [3, 4]])

In [13]:
a.shape

(2, 2)

In [17]:
b = np.array([[5, 6]])

In [18]:
b

array([[5, 6]])

In [19]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
b.T

array([[5],
       [6]])

In [22]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [23]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

In [26]:
yields.reshape(10000, 1).shape

(10000, 1)

In [27]:
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

In [28]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [29]:
np.savetxt('climate_results.csv', 
           climate_results, 
           fmt='%.2f', 
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples', 
           comments='')

# understanding array operations

In [21]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [22]:
arr3.shape

(3, 2, 4)

In [23]:
arr3[1, 1, 2]

36.0

In [26]:
arr3[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [25]:
arr3

array([[[11. , 12. , 13. , 14. ],
        [13. , 14. , 15. , 19. ]],

       [[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [35]:
arr3[1:, 1, 3]

array([18., 43.])

In [36]:
arr3[1:, 1, :3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [37]:
arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [38]:
arr3[:2, 1]

array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])

In [27]:
arr3[1,3,2,1]

IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

In [28]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [29]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [30]:
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [31]:
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [44]:
arr2 / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [45]:
arr2 * arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [46]:
arr2 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]])

In [47]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [48]:
arr2.shape

(3, 4)

In [36]:
arr4 = np.array([4, 5, 6, 7])

In [37]:
arr4.shape

(4,)

In [41]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [42]:
arr5 = np.array([7, 8])

In [43]:
arr5.shape

(2,)

In [44]:
arr2 + arr5

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In [45]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [46]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [47]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [48]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [49]:
arr1 < arr2

array([[ True, False, False],
       [False, False, False]])

In [50]:
(arr1 == arr2).sum()

3

In [51]:
test = np.random.random((5))

In [52]:
test

array([0.67261479, 0.8460695 , 0.73914354, 0.96267229, 0.33870986])

In [53]:
test[:2]

array([0.67261479, 0.8460695 ])